// cards.js
// Centralized card and rank definitions

export const RANKS = {
  C: { name: "C", color: 0x00A300, icon: "https://files.catbox.moe/8gn79p.png", value: 1 },
  B: { name: "B", color: 0x3498db, icon: "https://files.catbox.moe/rv1frd.png", value: 2 },
  A: { name: "A", color: 0x9b59b6, icon: "https://files.catbox.moe/ussec9.webp", value: 3 },
  S: { name: "S", color: 0xe74c3c, icon: "https://files.catbox.moe/wrx7hl.png", value: 4 },
  SS: { name: "SS", color: 0xff4000, icon: "https://files.catbox.moe/wvqbnp.webp", value: 5 }, // dark orange
  UR: { name: "UR", color: 0x8B0000, icon: "https://files.catbox.moe/200d01.webp", value: 6 }, // dark red
};

export const cards = [
  // LUFFY PROGRESSION - Chronological (Kid -> Dawn Island -> Captain -> Worst Gen -> Emperor -> Warrior)
  {
    id: "luffy_c_01",
    name: "Monkey D. Luffy",
    title: "Kid luffy",
    rank: "C",
    power: 30,
    attackRange: [5, 10],
    health: 80,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/kihgbn.jpg",
    evolutions: ["luffy_b_02"],
  },
  {
    id: "luffy_b_02",
    name: "Monkey D. Luffy",
    title: "Dawn Island",
    rank: "B",
    power: 90,
    attackRange: [16, 28],
    health: 140,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/530q7y.jpg",
    evolutions: ["luffy_a_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 1800, minLevel: 15 },
  },
  {
    id: "luffy_a_03",
    name: "Monkey D. Luffy",
    title: "Captain of the Straw Hat Pirates",
    rank: "A",
    power: 160,
    attackRange: [26, 44],
    health: 210,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/hkxjpn.jpg",
    evolutions: ["luffy_s_04"],
    isUpgrade: true,
    upgradeRequirements: { cost: 4500, minLevel: 28 },
  },
  {
    id: "luffy_s_04",
    name: "Monkey D. Luffy",
    title: "Worst Generation Pirate",
    rank: "S",
    power: 300,
    attackRange: [30, 70],
    health: 310,
    type: "Attack",
    specialAttack: { name: "Gear 4 Boundman", range: [90, 120] },
    ability: null,
    image: "https://files.catbox.moe/umvjn2.jpg",
    evolutions: ["luffy_ss_05"],
    isUpgrade: true,
    upgradeRequirements: { cost: 9000, minLevel: 40 },
  },
  {
    id: "luffy_ss_05",
    name: "Monkey D. Luffy",
    title: "Emperor of the Sea",
    rank: "SS",
    power: 600,
    attackRange: [80, 130],
    health: 520,
    type: "Attack",
    specialAttack: { name: "Gear 5 Nika Power (Limited)", range: [150, 200] },
    ability: null,
    image: "https://files.catbox.moe/08lgjd.jpg",
    evolutions: ["luffy_ur_06"],
    isUpgrade: true,
    upgradeRequirements: { cost: 35000, minLevel: 65 },
  },
  {
    id: "luffy_ur_06",
    name: "Monkey D. Luffy",
    title: "Warrior of Liberation",
    rank: "UR",
    power: 1150,
    attackRange: [120, 170],
    health: 780,
    type: "Attack",
    specialAttack: { name: "Gear 5 Nika Power", range: [200, 250] },
    ability: null,
    image: "https://files.catbox.moe/ppdc69.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 100000, minLevel: 100 },
  },
  // SABO
  {
    id: "sabo_c_01",
    name: "Sabo",
    title: "Kid Sabo (Goa Kingdom)",
    rank: "C",
    power: 28,
    attackRange: [8, 15],
    health: 75,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/2410ln.webp",
    evolutions: ["sabo_s_02"],
  },
  {
    id: "sabo_s_02",
    name: "Sabo",
    title: "Flame Emperor",
    rank: "S",
    power: 320,
    attackRange: [35, 65],
    health: 320,
    type: "Attack",
    specialAttack: { name: "Blazing Dragon King", range: [100, 150] },
    ability: null,
    image: "https://files.catbox.moe/axjzhp.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 8000, minLevel: 35 },
  },
  // MAKINO
  {
    id: "makino_c_01",
    name: "Makino",
    title: "Goa Kingdom",
    rank: "C",
    power: 15,
    attackRange: [3, 12],
    health: 60,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/6b03cg.webp",
    evolutions: ["makino_c_02"],
  },
  {
    id: "makino_c_02",
    name: "Makino",
    title: "Goa Kingdom (Post-Timeskip)",
    rank: "C",
    power: 35,
    attackRange: [7, 18],
    health: 85,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/3qa0bo.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 12 },
  },
  // MONKEY D GARP
  {
    id: "monkeydgarp_ss_01",
    name: "Monkey D. Garp",
    title: "Navy Vice Admiral (out of prime)",
    rank: "SS",
    power: 450,
    attackRange: [60, 110],
    health: 480,
    type: "Attack",
    specialAttack: { name: "Galaxy Impact", range: [140, 180] },
    ability: null,
    image: "https://files.catbox.moe/dvemqd.webp",
    evolutions: ["monkeydgarp_ss_02"],
  },
  {
    id: "monkeydgarp_ss_02",
    name: "Monkey D. Garp",
    title: "Training Arc (navy)",
    rank: "SS",
    power: 480,
    attackRange: [70, 115],
    health: 510,
    type: "Attack",
    specialAttack: { name: "Galaxy Impact", range: [150, 190] },
    ability: null,
    image: "https://files.catbox.moe/gd7oud.webp",
    evolutions: ["monkeydgarp_ur_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 32000, minLevel: 60 },
  },
  {
    id: "monkeydgarp_ur_03",
    name: "Monkey D. Garp",
    title: "Prime Garp (Godvalley)",
    rank: "UR",
    power: 480,
    attackRange: [90, 120],
    health: 480,
    type: "Attack",
    specialAttack: { name: "Galaxy Impact", range: [180, 240] },
    ability: null,
    image: "https://files.catbox.moe/zltzug.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 95000, minLevel: 95 },
  },
  // MONKEY D DRAGON
  {
    id: "monkeydragon_b_01",
    name: "Monkey D. Dragon",
    title: "Marine Officer",
    rank: "B",
    power: 65,
    attackRange: [14, 30],
    health: 130,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ax725x.webp",
    evolutions: ["monkeydragon_ss_02"],
  },
  {
    id: "monkeydragon_ss_02",
    name: "Monkey D. Dragon",
    title: "Founder of the Revolutionary Army",
    rank: "SS",
    power: 420,
    attackRange: [65, 105],
    health: 450,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/xurys2.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 30000, minLevel: 55 },
  },
  // PORTGAS D ACE
  {
    id: "portgasdace_b_01",
    name: "Portgas D. Ace",
    title: "Kid Ace (Goa Kingdom)",
    rank: "B",
    power: 70,
    attackRange: [12, 32],
    health: 145,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/91lisa.jpg",
    evolutions: ["portgasdace_s_02"],
  },
  {
    id: "portgasdace_s_02",
    name: "Portgas D. Ace",
    title: "Captain of the Spade Pirates",
    rank: "S",
    power: 280,
    attackRange: [32, 68],
    health: 300,
    type: "Attack",
    specialAttack: { name: "Fire Fist", range: [95, 145] },
    ability: null,
    image: "https://files.catbox.moe/hiw7wc.jpg",
    evolutions: ["portgasdace_s_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 7500, minLevel: 32 },
  },
  {
    id: "portgasdace_s_03",
    name: "Portgas D. Ace",
    title: "2nd Division Commander of the Whitebeard Pirates",
    rank: "S",
    power: 310,
    attackRange: [38, 72],
    health: 330,
    type: "Attack",
    specialAttack: { name: "Fire Fist", range: [110, 160] },
    ability: null,
    image: "https://files.catbox.moe/zqhyvx.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 8500, minLevel: 38 },
  },
  // CURLY DADAN
  {
    id: "curlydadan_c_01",
    name: "Curly Dadan",
    title: "Boss of the Dadan familly",
    rank: "C",
    power: 32,
    attackRange: [6, 16],
    health: 95,
    type: "Defense",
    ability: null,
    image: "https://files.catbox.moe/4b8wt3.webp",
    evolutions: ["curlydadan_c_02"],
  },
  // WOOP SLAP
  {
    id: "woopslap_c_01",
    name: "Woop Slap",
    title: "Mayor of Foosha Village",
    rank: "C",
    power: 18,
    attackRange: [4, 14],
    health: 65,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/kydhbn.webp",
    evolutions: ["woopslap_c_02"],
  },
  {
    id: "woopslap_c_02",
    name: "Woop Slap",
    title: "Mayor of Foosha Village",
    rank: "C",
    power: 28,
    attackRange: [9, 17],
    health: 78,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/1ymf59.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 11 },
  },
  // GOA KINGDOM CHARACTERS
  {
    id: "kingsterry_c_01",
    name: "King Sterry",
    title: "Goa Kingdom",
    rank: "C",
    power: 22,
    attackRange: [5, 13],
    health: 70,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/yymvei.webp",
    evolutions: [],
  },
  {
    id: "queensarienantkokanette_c_01",
    name: "Queen Sarie Nantokanette",
    title: "Goa Kingdom",
    rank: "C",
    power: 20,
    attackRange: [6, 14],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/smnu9v.webp",
    evolutions: [],
  },
  {
    id: "outlookiii_c_01",
    name: "Outlook III",
    title: "Goa Kingdom",
    rank: "C",
    power: 25,
    attackRange: [7, 15],
    health: 72,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/iaw48k.webp",
    evolutions: [],
  },
  {
    id: "didit_c_01",
    name: "Didit",
    title: "Goa Kingdom",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 65,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/tainz3.webp",
    evolutions: [],
  },
  {
    id: "ahhodesneix_c_01",
    name: "Ahho Desunen IX",
    title: "Goa Kingdom",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/2js3ks.webp",
    evolutions: [],
  },
  {
    id: "ahhozurako_c_01",
    name: "Ahho Zurako",
    title: "Goa Kingdom",
    rank: "C",
    power: 19,
    attackRange: [5, 12],
    health: 66,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/7uohkt.webp",
    evolutions: [],
  },
  {
    id: "gyoru_c_01",
    name: "Gyoru",
    title: "Goa Kingdom",
    rank: "C",
    power: 24,
    attackRange: [6, 14],
    health: 71,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/4qhte5.webp",
    evolutions: [],
  },
  {
    id: "chicken_c_01",
    name: "Chicken",
    title: "Goa Kingdom",
    rank: "C",
    power: 12,
    attackRange: [2, 10],
    health: 50,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/xk7u3d.webp",
    evolutions: [],
  },
  {
    id: "makinoschild_c_01",
    name: "Makino's Child",
    title: "Goa Kingdom",
    rank: "C",
    power: 10,
    attackRange: [1, 8],
    health: 52,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/56iyfh.webp",
    evolutions: [],
  },
  {
    id: "dogra_c_01",
    name: "Dogra",
    title: "Goa Kingdom",
    rank: "C",
    power: 26,
    attackRange: [8, 16],
    health: 74,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/x8ndw2.webp",
    evolutions: [],
  },
  {
    id: "magra_c_01",
    name: "Magra",
    title: "Goa Kingdom",
    rank: "C",
    power: 27,
    attackRange: [8, 17],
    health: 75,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/a3xpgk.webp",
    evolutions: [],
  },
  {
    id: "minatomo_c_01",
    name: "Minatomo",
    title: "Goa Kingdom",
    rank: "C",
    power: 23,
    attackRange: [6, 14],
    health: 70,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/cqg9mv.webp",
    evolutions: [],
  },
  {
    id: "lordofthecoast_b_01",
    name: "Lord of the Coast",
    title: "Goa Kingdom",
    rank: "B",
    power: 75,
    attackRange: [18, 32],
    health: 160,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/8nzeq9.webp",
    evolutions: [],
  },
  {
    id: "higuma_c_01",
    name: "Higuma",
    title: "Goa Kingdom",
    rank: "C",
    power: 35,
    attackRange: [12, 18],
    health: 90,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ck22xb.webp",
    evolutions: [],
  },
  {
    id: "naguri_c_01",
    name: "Naguri",
    title: "Goa Kingdom",
    rank: "C",
    power: 30,
    attackRange: [9, 16],
    health: 82,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/x0xc8f.webp",
    evolutions: [],
  },
  {
    id: "pochi_c_01",
    name: "Pochi",
    title: "Goa Kingdom",
    rank: "C",
    power: 16,
    attackRange: [3, 11],
    health: 58,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/0y6dzn.webp",
    evolutions: [],
  },
  {
    id: "gillan_c_01",
    name: "Gillan",
    title: "Goa Kingdom",
    rank: "C",
    power: 21,
    attackRange: [5, 13],
    health: 69,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/3g8e89.webp",
    evolutions: [],
  },
  // HELMEPPO
  {
    id: "helmeppo_c_01",
    name: "Helmeppo",
    title: "Son of Axe-Hand Morgan",
    rank: "C",
    power: 20,
    attackRange: [4, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/i9od9u.webp",
    evolutions: ["helmeppo_a_02"],
  },
  {
    id: "helmeppo_a_02",
    name: "Helmeppo",
    title: "Lieutenant Commander",
    rank: "A",
    power: 130,
    attackRange: [22, 46],
    health: 190,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/do4myu.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 3800, minLevel: 25 },
  },
  // KOBY
  {
    id: "koby_c_01",
    name: "Koby",
    title: "Cabin Boy of the Alvida Pirates",
    rank: "C",
    power: 15,
    attackRange: [3, 11],
    health: 62,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/djvysx.jpg",
    evolutions: ["koby_a_02"],
  },
  {
    id: "koby_a_02",
    name: "Koby",
    title: "Marine Officer",
    rank: "A",
    power: 120,
    attackRange: [20, 44],
    health: 180,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ujmo0b.webp",
    evolutions: ["koby_s_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 3600, minLevel: 24 },
  },
  {
    id: "koby_s_03",
    name: "Koby",
    title: "Marine Captain",
    rank: "S",
    power: 260,
    attackRange: [30, 65],
    health: 310,
    type: "Support",
    specialAttack: { name: "Galaxy Impact", range: [100, 150] },
    ability: null,
    image: "https://files.catbox.moe/nu2u2g.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 7200, minLevel: 33 },
  },
  // SHELLS TOWN CHARACTERS
  {
    id: "rika_c_01",
    name: "Rika",
    title: "Shells Town",
    rank: "C",
    power: 10,
    attackRange: [2, 9],
    health: 55,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/w0pead.webp",
    evolutions: [],
  },
  {
    id: "ririka_c_01",
    name: "Ririka",
    title: "Shells Town",
    rank: "C",
    power: 12,
    attackRange: [3, 10],
    health: 58,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/azd1gb.webp",
    evolutions: [],
  },
  {
    id: "ukkari_c_01",
    name: "Ukkari",
    title: "Shells Town",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 65,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/xd6gx4.webp",
    evolutions: [],
  },
  {
    id: "rokkaku_c_01",
    name: "Rokkaku",
    title: "Shells Town",
    rank: "C",
    power: 22,
    attackRange: [5, 13],
    health: 70,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/n7xrnm.webp",
    evolutions: [],
  },
  {
    id: "ripper_c_01",
    name: "Ripper",
    title: "Shells Town",
    rank: "C",
    power: 25,
    attackRange: [7, 15],
    health: 72,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/41cavp.webp",
    evolutions: [],
  },
  {
    id: "axehandmorgan_b_01",
    name: "Axe-Hand Morgan",
    title: "Shells Town",
    rank: "B",
    power: 85,
    attackRange: [16, 34],
    health: 170,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/hwzr92.webp",
    evolutions: [],
  },
  {
    id: "soro_c_01",
    name: "Soro",
    title: "Shells Town",
    rank: "C",
    power: 16,
    attackRange: [4, 11],
    health: 60,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/jv8td8.webp",
    evolutions: [],
  },
  {
    id: "marinex_c_01",
    name: "Marine X",
    title: "Shells Town",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/7p69bl.webp",
    evolutions: [],
  },
  {
    id: "sada_c_01",
    name: "Sada",
    title: "Shells Town",
    rank: "C",
    power: 19,
    attackRange: [5, 12],
    health: 66,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/49e50f.webp",
    evolutions: [],
  },
  // RORONOA ZORO
  {
    id: "roronoazoro_c_01",
    name: "Roronoa Zoro",
    title: "Kid zoro",
    rank: "C",
    power: 32,
    attackRange: [8, 16],
    health: 78,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/0jrih7.jpg",
    signatureWeapon: "wadoichimonji_ss_01",
    evolutions: ["roronoazoro_a_02"],
  },
  {
    id: "roronoazoro_a_02",
    name: "Roronoa Zoro",
    title: "Pirate hunter",
    rank: "A",
    power: 140,
    attackRange: [24, 48],
    health: 210,
    type: "Attack",
    specialAttack: { name: "Oni Giri", range: [85, 135] },
    ability: null,
    image: "https://files.catbox.moe/6bgu26.webp",
    signatureWeapon: "wadoichimonji_ss_01",
    evolutions: ["roronoazoro_a_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 4000, minLevel: 26 },
  },
  {
    id: "roronoazoro_a_03",
    name: "Roronoa Zoro",
    title: "Crewmate of the Strawhat Pirates",
    rank: "A",
    power: 165,
    attackRange: [28, 50],
    health: 230,
    type: "Attack",
    specialAttack: { name: "Nine-Sword Style - Ashura", range: [95, 145] },
    ability: null,
    image: "https://files.catbox.moe/xz71jk.png",
    signatureWeapon: "wadoichimonji_ss_01",
    evolutions: ["roronoazoro_s_04"],
    isUpgrade: true,
    upgradeRequirements: { cost: 4800, minLevel: 30 },
  },
  {
    id: "roronoazoro_s_04",
    name: "Roronoa Zoro",
    title: "part of the worst generation",
    rank: "S",
    power: 290,
    attackRange: [34, 68],
    health: 320,
    type: "Attack",
    specialAttack: { name: "Rengoku Oni Giri", range: [105, 160] },
    ability: null,
    image: "https://files.catbox.moe/ulknow.jpg",
    signatureWeapon: "wadoichimonji_ss_01",
    evolutions: ["roronoazoro_ss_05"],
    isUpgrade: true,
    upgradeRequirements: { cost: 8200, minLevel: 37 },
  },
  {
    id: "roronoazoro_ss_05",
    name: "Roronoa Zoro",
    title: "King of Hell",
    rank: "SS",
    power: 480,
    attackRange: [70, 115],
    health: 490,
    type: "Attack",
    specialAttack: { name: "Nine-Sword Style: Asura - Blades Drawn, Dead Man's Game", range: [160, 210] },
    ability: null,
    image: "https://files.catbox.moe/ik3fjn.jpg",
    signatureWeapon: "wadoichimonji_ss_01",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 28000, minLevel: 50 },
  },
  // SHIMOTSUKI VILLAGE CHARACTERS
  {
    id: "shimotsukikushiru_b_01",
    name: "Shimotsuki Kushiru",
    title: "Shimotsuki Village",
    rank: "B",
    power: 70,
    attackRange: [15, 31],
    health: 145,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/cvj7dy.webp",
    evolutions: [],
  },
  {
    id: "shimotsukikuina_b_01",
    name: "Shimotsuki Kuina",
    title: "Shimotsuki Village",
    rank: "B",
    power: 75,
    attackRange: [18, 33],
    health: 155,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ge8y9x.webp",
    signatureWeapon: "wadoichimonji_ss_01",
    evolutions: [],
  },
  {
    id: "shimotsukikouzaburou_b_01",
    name: "Shimotsuki Kouzaburou",
    title: "Shimotsuki Village",
    rank: "B",
    power: 76,
    attackRange: [19, 34],
    health: 160,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/kuvu3p.webp",
    evolutions: [],
  },
  {
    id: "himari_c_01",
    name: "Himari",
    title: "Shimotsuki Village",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/lvt93d.webp",
    evolutions: [],
  },
  {
    id: "saga_a_01",
    name: "Saga",
    title: "Shimotsuki Village",
    rank: "A",
    power: 145,
    attackRange: [25, 48],
    health: 220,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/idr499.webp",
    evolutions: [],
  },
  // BOODLE
  {
    id: "boodle_c_01",
    name: "Boodle",
    title: "Mayor of Orange Town",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 65,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/a6sqc3.webp",
    evolutions: ["boodle_c_02"],
  },
  {
    id: "boodle_c_02",
    name: "Boodle",
    title: "Mayor of orange Town",
    rank: "C",
    power: 24,
    attackRange: [6, 14],
    health: 71,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/1iy7xs.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 11 },
  },
  // CHOUCHOU
  {
    id: "chouchou_c_01",
    name: "ChouChou",
    title: "Orange Town",
    rank: "C",
    power: 15,
    attackRange: [3, 11],
    health: 62,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/q8cg55.webp",
    evolutions: ["chouchou_c_02"],
  },
  {
    id: "chouchou_c_02",
    name: "ChouChou",
    title: "Orange Town",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/f4a3cf.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1100, minLevel: 10 },
  },
  // PORO
  {
    id: "poro_c_01",
    name: "Poro",
    title: "Orange Town",
    rank: "C",
    power: 16,
    attackRange: [4, 11],
    health: 60,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/w9al2n.webp",
    evolutions: ["poro_c_02"],
  },
  {
    id: "poro_c_02",
    name: "Poro",
    title: "Orange Town",
    rank: "C",
    power: 21,
    attackRange: [5, 13],
    health: 69,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/w6xl13.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1100, minLevel: 10 },
  },
  // HOCKER
  {
    id: "hocker_c_01",
    name: "Hocker",
    title: "Orange Town",
    rank: "C",
    power: 19,
    attackRange: [4, 12],
    health: 66,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/y5c05w.webp",
    evolutions: [],
  },
  // GAIMON
  {
    id: "gaimon_c_01",
    name: "Gaimon",
    title: "Marksman of Unnamed Crew",
    rank: "C",
    power: 28,
    attackRange: [7, 15],
    health: 76,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/c66k4n.webp",
    evolutions: ["gaimon_c_02"],
  },
  {
    id: "gaimon_c_02",
    name: "Gaimon",
    title: "Guardian of the Island of Rare Animals (yes he got stronger.)",
    rank: "C",
    power: 32,
    attackRange: [9, 17],
    health: 80,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/b96lzc.webp",
    evolutions: ["gaimon_c_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 1300, minLevel: 12 },
  },
  // ISLAND OF RARE ANIMALS CHARACTERS
  {
    id: "sarfunkel_c_01",
    name: "Sarfunkel",
    title: "Island of rare animals",
    rank: "C",
    power: 22,
    attackRange: [5, 13],
    health: 70,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/blz2zk.webp",
    evolutions: [],
  },
  {
    id: "cocox_c_01",
    name: "Cocox",
    title: "Island of rare animals",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 65,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/m5bfq4.webp",
    evolutions: [],
  },
  {
    id: "unsagihebi_c_01",
    name: "Unsagihebi",
    title: "Island of rare animals",
    rank: "C",
    power: 26,
    attackRange: [7, 15],
    health: 74,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ecagnd.webp",
    evolutions: [],
  },
  {
    id: "lionbuta_c_01",
    name: "Lionbuta",
    title: "Island of rare animals",
    rank: "C",
    power: 29,
    attackRange: [8, 16],
    health: 78,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/arkd42.webp",
    evolutions: [],
  },
  {
    id: "kirinkodanuki_c_01",
    name: "Kirinkodanuki",
    title: "Island of rare animals",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/g5762z.webp",
    evolutions: [],
  },
  {
    id: "kabagorilla_c_01",
    name: "KabaGorilla",
    title: "Island of rare animals",
    rank: "C",
    power: 31,
    attackRange: [9, 17],
    health: 80,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/f4beoj.webp",
    evolutions: [],
  },
  {
    id: "kamohitsuji_c_01",
    name: "Kamohitsuji",
    title: "Island of rare animals",
    rank: "C",
    power: 17,
    attackRange: [4, 11],
    health: 61,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/w2htv4.webp",
    evolutions: [],
  },
  {
    id: "saikangaroo_c_01",
    name: "Saikangaroo",
    title: "Island of rare animals",
    rank: "C",
    power: 23,
    attackRange: [6, 14],
    health: 70,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/7j5vx8.webp",
    evolutions: [],
  },
  // USOPP
  {
    id: "usopp_c_01",
    name: "Usopp",
    title: "Kid usopp",
    rank: "C",
    power: 16,
    attackRange: [3, 11],
    health: 60,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/y1g60e.jpg",
    evolutions: ["usopp_c_02"],
  },
  {
    id: "usopp_c_02",
    name: "Usopp",
    title: "Captain of the Usopp Pirates",
    rank: "C",
    power: 24,
    attackRange: [6, 14],
    health: 71,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/sy77mg.webp",
    evolutions: ["usopp_c_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 11 },
  },
  {
    id: "usopp_c_03",
    name: "Usopp",
    title: "SOGEEEEKINGGGG!!!!",
    rank: "C",
    power: 28,
    attackRange: [7, 15],
    health: 76,
    type: "Support",
    specialAttack: { name: "Rubber band of Doom", range: [75, 110] },
    ability: null,
    image: "https://files.catbox.moe/ir1an0.jpg",
    evolutions: ["usopp_b_04"],
    isUpgrade: true,
    upgradeRequirements: { cost: 1400, minLevel: 13 },
  },
  {
    id: "usopp_b_04",
    name: "Usopp",
    title: "God Usopp",
    rank: "B",
    power: 85,
    attackRange: [16, 34],
    health: 170,
    type: "Support",
    specialAttack: { name: "Cherry 分쇄 (Pound)", range: [95, 140] },
    ability: null,
    image: "https://files.catbox.moe/c5sl6v.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 3200, minLevel: 22 },
  },
  // YASSOP
  {
    id: "yassop_a_01",
    name: "Yassop",
    title: "Senior Officer of the Red-Haired Pirates",
    rank: "A",
    power: 155,
    attackRange: [28, 50],
    health: 240,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/vzt741.webp",
    evolutions: [],
  },
  // KAYA
  {
    id: "kaya_c_01",
    name: "Kaya",
    title: "Medical Student",
    rank: "C",
    power: 12,
    attackRange: [2, 10],
    health: 58,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/407da6.webp",
    evolutions: ["kaya_c_02"],
  },
  {
    id: "kaya_c_02",
    name: "Kaya",
    title: "Medical Student",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 65,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/5m6pvw.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1100, minLevel: 10 },
  },
  // MERRY
  {
    id: "merry_c_01",
    name: "Merry",
    title: "Butler",
    rank: "C",
    power: 14,
    attackRange: [3, 11],
    health: 59,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/3pztp5.webp",
    evolutions: ["merry_c_02"],
  },
  {
    id: "merry_c_02",
    name: "Merry",
    title: "Butler",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/73ggr0.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1100, minLevel: 10 },
  },
  // NINJIN
  {
    id: "ninjin_c_01",
    name: "Ninjin",
    title: "pretend pirate",
    rank: "C",
    power: 11,
    attackRange: [2, 9],
    health: 54,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/tme4w4.webp",
    evolutions: ["ninjin_c_02"],
  },
  {
    id: "ninjin_c_02",
    name: "Ninjin",
    title: "pretend pirate",
    rank: "C",
    power: 17,
    attackRange: [4, 12],
    health: 62,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/5zon73.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1000, minLevel: 9 },
  },
  // TAMANEGI
  {
    id: "tamanegi_c_01",
    name: "Tamanegi",
    title: "pretend pirate",
    rank: "C",
    power: 13,
    attackRange: [3, 10],
    health: 57,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/k3b74l.webp",
    evolutions: ["tamanegi_c_02"],
  },
  {
    id: "tamanegi_c_02",
    name: "Tamanegi",
    title: "pretend pirate",
    rank: "C",
    power: 19,
    attackRange: [4, 12],
    health: 66,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/j6aghh.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1100, minLevel: 10 },
  },
  // PIIMAN
  {
    id: "piiman_c_01",
    name: "Piiman",
    title: "pretend pirate",
    rank: "C",
    power: 12,
    attackRange: [2, 10],
    health: 56,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/drhge8.webp",
    evolutions: ["piiman_c_02"],
  },
  {
    id: "piiman_c_02",
    name: "Piiman",
    title: "pretend pirate",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 64,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/84r4s3.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1000, minLevel: 9 },
  },
  // KURO
  {
    id: "kuro_b_01",
    name: "Kuro",
    title: "Captain of the Black Cat Pirates",
    rank: "B",
    power: 88,
    attackRange: [18, 34],
    health: 175,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/qqzd49.webp",
    evolutions: ["kuro_b_02"],
  },
  {
    id: "kuro_b_02",
    name: "Kuro",
    title: "Butler",
    rank: "B",
    power: 95,
    attackRange: [20, 36],
    health: 190,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/mz1pyn.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 3500, minLevel: 23 },
  },
  // SYRUP VILLAGE CHARACTERS
  {
    id: "banchina_c_01",
    name: "Banchina",
    title: "Syrup Village",
    rank: "C",
    power: 10,
    attackRange: [2, 9],
    health: 55,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/1jo5vk.webp",
    evolutions: [],
  },
  {
    id: "mornin_c_01",
    name: "Mornin",
    title: "Syrup Village",
    rank: "C",
    power: 14,
    attackRange: [3, 11],
    health: 59,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/6w8jov.webp",
    evolutions: [],
  },
  {
    id: "luigia_c_01",
    name: "Luigia",
    title: "Syrup Village",
    rank: "C",
    power: 16,
    attackRange: [4, 11],
    health: 61,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/36gbby.webp",
    evolutions: [],
  },
  {
    id: "mansionsguards_c_01",
    name: "Mansion's Guards",
    title: "Syrup Village",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/yezy55.webp",
    evolutions: [],
  },
  // ZEFF
  {
    id: "zeff_b_01",
    name: "Zeff",
    title: "Out of Prime, Head Chef of Baratie",
    rank: "B",
    power: 80,
    attackRange: [14, 30],
    health: 160,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/hyfwol.webp",
    evolutions: ["zeff_a_02"],
  },
  {
    id: "zeff_a_02",
    name: "Zeff",
    title: "Captain of the Cook Pirates",
    rank: "A",
    power: 160,
    attackRange: [28, 50],
    health: 250,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/bl5132.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 4500, minLevel: 28 },
  },
  // PATTY
  {
    id: "patty_c_01",
    name: "Patty",
    title: "Baratie's Patissier",
    rank: "C",
    power: 19,
    attackRange: [4, 12],
    health: 66,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/do9thv.webp",
    evolutions: ["patty_b_02"],
  },
  {
    id: "patty_b_02",
    name: "Patty",
    title: "Baratie's Patissier",
    rank: "B",
    power: 78,
    attackRange: [13, 29],
    health: 155,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/09kam1.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 2800, minLevel: 19 },
  },
  // CARNE
  {
    id: "carne_c_01",
    name: "Carne",
    title: "Baraties Charcutier",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 65,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/g0e7b1.webp",
    evolutions: ["carne_c_02"],
  },
  {
    id: "carne_c_02",
    name: "Carne",
    title: "Baratie's Charcutier",
    rank: "C",
    power: 25,
    attackRange: [6, 14],
    health: 72,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/bvwkk2.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 11 },
  },
  // VINSMOKE SANJI
  {
    id: "vinsmokesanji_c_01",
    name: "Vinsmoke Sanji",
    title: "Kid Sanji (Germa Kingdom)",
    rank: "C",
    power: 22,
    attackRange: [5, 13],
    health: 70,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/uztd7s.jpg",
    evolutions: ["vinsmokesanji_c_02"],
  },
  {
    id: "vinsmokesanji_c_02",
    name: "Vinsmoke Sanji",
    title: "Kid Sanji (baratie)",
    rank: "C",
    power: 27,
    attackRange: [7, 15],
    health: 75,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/a2fdyu.jpg",
    evolutions: ["vinsmokesanji_s_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 1300, minLevel: 12 },
  },
  {
    id: "vinsmokesanji_s_03",
    name: "Vinsmoke Sanji",
    title: "Sous Chef",
    rank: "S",
    power: 285,
    attackRange: [32, 68],
    health: 310,
    type: "Attack",
    specialAttack: { name: "Diable Jambe", range: [105, 155] },
    ability: null,
    image: "https://files.catbox.moe/9xr1k3.jpg",
    evolutions: ["vinsmokesanji_s_04"],
    isUpgrade: true,
    upgradeRequirements: { cost: 7500, minLevel: 34 },
  },
  {
    id: "vinsmokesanji_s_04",
    name: "Vinsmoke Sanji",
    title: "Crewmember of the Strawhat Pirates",
    rank: "S",
    power: 310,
    attackRange: [36, 70],
    health: 330,
    type: "Attack",
    specialAttack: { name: "Diable Jambe", range: [115, 165] },
    ability: null,
    image: "https://files.catbox.moe/rocqrh.webp",
    evolutions: ["vinsmokesanji_s_05"],
    isUpgrade: true,
    upgradeRequirements: { cost: 8500, minLevel: 38 },
  },
  {
    id: "vinsmokesanji_s_05",
    name: "Vinsmoke Sanji",
    title: "Black Leg",
    rank: "S",
    power: 335,
    attackRange: [38, 72],
    health: 350,
    type: "Attack",
    specialAttack: { name: "Diable Jambe", range: [120, 170] },
    ability: null,
    image: "https://files.catbox.moe/z5u2y0.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 9500, minLevel: 42 },
  },
  // NAMI
  {
    id: "nami_c_01",
    name: "Nami",
    title: "Kid Nami (Cocoyasi Village)",
    rank: "C",
    power: 14,
    attackRange: [3, 11],
    health: 59,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ugjrxn.jpg",
    evolutions: ["nami_c_02"],
  },
  {
    id: "nami_c_02",
    name: "Nami",
    title: "Cat burglar",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/fb1qp1.webp",
    evolutions: ["nami_b_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 11 },
  },
  {
    id: "nami_b_03",
    name: "Nami",
    title: "Crewmember of the Strawhat Pirates",
    rank: "B",
    power: 92,
    attackRange: [20, 36],
    health: 185,
    type: "Support",
    specialAttack: { name: "Thunder Lance Tempo", range: [110, 155] },
    ability: null,
    image: "https://files.catbox.moe/xtrg7h.jpg",
    evolutions: ["nami_a_04"],
    isUpgrade: true,
    upgradeRequirements: { cost: 4200, minLevel: 27 },
  },
  {
    id: "nami_a_04",
    name: "Nami",
    title: "Crewmember of the Strawhat Pirates",
    rank: "A",
    power: 170,
    attackRange: [32, 50],
    health: 240,
    type: "Support",
    specialAttack: { name: "Zeus Breeze Tempo", range: [125, 175] },
    ability: null,
    image: "https://files.catbox.moe/a5acsm.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 5500, minLevel: 32 },
  },
  // NOJIKO
  {
    id: "nojiko_c_01",
    name: "Nojiko",
    title: "Kid Nojiko (Cocoyasi Village)",
    rank: "C",
    power: 12,
    attackRange: [2, 10],
    health: 57,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/0gfj06.webp",
    evolutions: ["nojiko_c_02"],
  },
  {
    id: "nojiko_c_02",
    name: "Nojiko",
    title: "Mikan Farmer",
    rank: "C",
    power: 19,
    attackRange: [4, 12],
    health: 66,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/hs3byg.webp",
    evolutions: ["nojiko_c_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 1100, minLevel: 10 },
  },
  {
    id: "nojiko_c_03",
    name: "Nojiko",
    title: "Mikan Farmer",
    rank: "C",
    power: 24,
    attackRange: [6, 14],
    health: 71,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/hs3byg.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 11 },
  },
  // GENZO
  {
    id: "genzo_b_01",
    name: "Genzo",
    title: "Sherrif of Cocoyasi Village",
    rank: "B",
    power: 82,
    attackRange: [15, 31],
    health: 165,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/k0bm8f.webp",
    evolutions: ["genzo_b_02"],
  },
  {
    id: "genzo_b_02",
    name: "Genzo",
    title: "Sherif of Cocoyasi Village",
    rank: "B",
    power: 88,
    attackRange: [17, 32],
    health: 175,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/boye4w.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 3200, minLevel: 21 },
  },
  // JHONNY
  {
    id: "jhonny_c_01",
    name: "Jhonny",
    title: "Bounty Hunter",
    rank: "C",
    power: 21,
    attackRange: [5, 13],
    health: 69,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/s5d98s.webp",
    evolutions: ["jhonny_c_02"],
  },
  {
    id: "jhonny_c_02",
    name: "Jhonny",
    title: "Fisherman",
    rank: "C",
    power: 26,
    attackRange: [7, 15],
    health: 74,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/wiz0ca.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1200, minLevel: 11 },
  },
  // YOSAKU
  {
    id: "yosaku_c_01",
    name: "Yosaku",
    title: "Bounty Hunter",
    rank: "C",
    power: 23,
    attackRange: [6, 14],
    health: 70,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/jrnxqx.webp",
    evolutions: ["yosaku_c_02"],
  },
  {
    id: "yosaku_c_02",
    name: "Yosaku",
    title: "Fisherman",
    rank: "C",
    power: 28,
    attackRange: [7, 15],
    health: 76,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/90coom.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1300, minLevel: 12 },
  },
  // CONOMI ISLANDS CHARACTERS
  {
    id: "nako_c_01",
    name: "Nako",
    title: "Conomi Islands",
    rank: "C",
    power: 15,
    attackRange: [3, 11],
    health: 60,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/wqdazz.webp",
    evolutions: [],
  },
  {
    id: "chabo_c_01",
    name: "Chabo",
    title: "Conomi Islands",
    rank: "C",
    power: 17,
    attackRange: [4, 12],
    health: 62,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/jy4rs7.webp",
    evolutions: ["chabo_c_02"],
  },
  {
    id: "chabo_c_02",
    name: "Chabo",
    title: "Conomi Islands",
    rank: "C",
    power: 22,
    attackRange: [5, 13],
    health: 70,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/mrfud5.webp",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1100, minLevel: 10 },
  },
  {
    id: "mummymee_c_01",
    name: "Mummy Mee",
    title: "Conomi Islands",
    rank: "C",
    power: 19,
    attackRange: [4, 12],
    health: 66,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/9j0bv4.webp",
    evolutions: [],
  },
  {
    id: "daddydee_c_01",
    name: "Daddy Dee",
    title: "Conomi Islands",
    rank: "C",
    power: 20,
    attackRange: [5, 13],
    health: 68,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/rxzgit.webp",
    evolutions: [],
  },
  {
    id: "sam_c_01",
    name: "Sam",
    title: "Conomi Islands",
    rank: "C",
    power: 18,
    attackRange: [4, 12],
    health: 64,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/tru671.webp",
    evolutions: [],
  },
  // WEAPONS
  {
    id: "wadoichimonji_ss_01",
    name: "Wado Ichimonnji",
    title: "Roronoa Zoro's weapon",
    rank: "SS",
    type: "weapon",
    boost: { atk: 20, spd: 0, hp: 0 },
    signatureCards: ["roronoazoro_c_01", "roronoazoro_a_02", "roronoazoro_a_03", "roronoazoro_s_04", "roronoazoro_ss_05", "shimotsukikuina_b_01"],
    mainCard: "roronoazoro_s_04",
    image: "https://files.catbox.moe/z99v28.webp",
    craftingRequirements: {
      materials: {
        "Steel": 5,
        "Iron": 3,
        "Wood": 3
      },
      cost: 5000
    },
    evolutions: ["wadoichimonji_blueprint_ss_01"],
  },
  // WEAPON BLUEPRINTS
  {
    id: "wadoichimonji_blueprint_ss_01",
    name: "Wado Ichimonji Blueprint",
    title: "Roronoa Zoro's weapon blueprint",
    rank: "SS",
    type: "item",
    ability: "Blueprint for crafting Wado Ichimonji",
    image: "https://files.catbox.moe/z99v28.webp",
    evolutions: ["wadoichimonji_ss_01"],
    isUpgrade: false,
  },
];


export function getCardById(id) {
  return cards.find((c) => c.id === id) || null;
}

// Probability-driven random card selection
// probabilities is an object with rank keys -> percentage (summing to 100)
export function getRandomCardByProbability(probabilities = { C: 50, B: 30, A: 15, S: 3, ITEM: 2 }) {
  const entries = Object.entries(probabilities);
  const rnd = Math.random() * 100;
  let acc = 0;
  let chosenRank = null;
  for (const [rank, pct] of entries) {
    acc += pct;
    if (rnd <= acc) {
      chosenRank = rank;
      break;
    }
  }
  if (!chosenRank || chosenRank === "ITEM") chosenRank = "C";
  // exclude upgraded versions from pulls
  const pool = cards.filter((c) => !c.isUpgrade && c.rank && c.rank.toUpperCase() === String(chosenRank).toUpperCase());
  if (pool.length > 0) return pool[Math.floor(Math.random() * pool.length)];
  // fallback should also exclude upgrade variants so evolved cards are never pullable
  const fallback = cards.filter((c) => !c.isUpgrade && c.rank && c.rank.toUpperCase() !== "ITEM");
  if (fallback.length > 0) return fallback[Math.floor(Math.random() * fallback.length)];
  const nonUpgrade = cards.filter((c) => !c.isUpgrade);
  return nonUpgrade.length > 0 ? nonUpgrade[Math.floor(Math.random() * nonUpgrade.length)] : cards[Math.floor(Math.random() * cards.length)];
}

export function getRankInfo(rank) {
  return RANKS[String(rank).toUpperCase()] || null;
}
